spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/471418051/Always-in-my-heart.git
          search-paths:
            - Always-in-my-heart
      label: master
#ğŸ’Ÿeureka
eureka:
  client:
    #ğŸ’Ÿ è¡¨ç¤ºæ˜¯å¦å°†è‡ªå·±æ³¨å†Œè¿›EurekaServer,é»˜è®¤ä¸º true
    register-with-eureka: true
    #ğŸ’Ÿ æ˜¯å¦ä»EurekaServeræŠ“å–å·²æœ‰çš„æ³¨å†Œä¿¡æ¯,é»˜è®¤ä¸º true,å•èŠ‚ç‚¹æ— æ‰€è°“,é›†ç¾¤å¿…é¡»è®¾ç½®ä¸º trueæ‰èƒ½é…åˆribbonä½¿ç”¨è´Ÿè½½å‡è¡¡
    fetch-registry: true
    service-url:
      defaultZone: http://eureka-server:7001/eureka,http://eureka-server-clan:7002/eureka,http://eureka-server-colony:7003/eureka
  instance:
    #ğŸŒ¾ ä¿®æ”¹ eureka client ä¸»æœºå
    instance-id: config-server
    #ğŸŒ¾ è®¿é—®è·¯å¾„å¼€å¯ipåœ°å€æ˜¾ç¤º
    prefer-ip-address: true
    #ğŸŒ¾ Eurekaå®¢æˆ·ç«¯å‘æœåŠ¡ç«¯å‘é€å¿ƒè·³çš„æ—¶é—´é—´éš”,å•ä½ä¸ºç§’(é»˜è®¤30ç§’)
    lease-renewal-interval-in-seconds: 30
    #ğŸŒ¾ EurekaæœåŠ¡ç«¯åœ¨æ”¶åˆ°æœ€åä¸€æ¬¡å¿ƒè·³åç­‰å¾…çš„æ—¶é—´ä¸Šçº¿,å•ä½ä¸ºç§’(é»˜è®¤æ˜¯90ç§’),è¶…æ—¶å°†ä¸å¯ç”¨æœåŠ¡è¢«åŠæ—¶ä»æ³¨å†Œä¸­å¿ƒæ¸…é™¤
    lease-expiration-duration-in-seconds: 90
#ğŸ’Ÿversion
message:
  info: Config Server version_4.0